hmrc/pillar2-submission-api

- .scalafix.conf
- app/uk/gov/hmrc/pillar2submissionapi/config/AppConfig.scala
- app/uk/gov/hmrc/pillar2submissionapi/controllers/MicroserviceHelloWorldController.scala
- app/uk/gov/hmrc/pillar2submissionapi/controllers/platform/DocumentationController.scala
- build.sbt
- project/plugins.sbt
As title implies, added scalafix to this project. Nothing much changed besides spacing/organisation of imports across classes
> [PIL-1149] added scalafix & applied reported fixes

- app/uk/gov/hmrc/pillar2submissionapi/config/AppConfig.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
Add commands for build and linting
> [PIL-1155] Add prePrChecks command

- conf/app.routes
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/definition.json
Fix the API context, which is currently blocking deployment
> [PIL-1277] Fix API context

- conf/application.conf
> [PIL-1339] explicitily disable auditing

- resources/public/api/definition.json
> [PIL-1277] remove scopes from definition.json

- README.md
- app/uk/gov/hmrc/pillar2submissionapi/controllers/JokeController.scala
- build.sbt
- conf/app.routes
- conf/application.conf
- conf/logback.xml
- it/test/uk/gov/hmrc/pillar2submissionapi/HealthEndpointIntegrationSpec.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/uk/gov/hmrc/pillar2submissionapi/controllers/JokeControllerSpec.scala
> [PIL-1195] fix pr-bot and update dependencies

- project/JsonToYaml.scala
- Remove package path from models/refs
- Remove redundant quotes
> PIL-1335: Improve formatting of generated OAS

- app/uk/gov/hmrc/pillar2submissionapi/controllers/UktrSubmissionController.scala
- build.sbt
- conf/app.routes
- project/plugins.sbt
Added tpolecat plugin to enforce stricter code quality rules.
> PIL-1154 Add tpolecat plugin

- README.md
Document the generation, validation and publishing processes following the OAS-from-routes generation.
> PIL-1337:  README.md - outline OAS generation, validation and publishing processes

- resources/public/api/definition.json
> Enabled UKTR submission endpoint

- resources/public/api/definition.json
Added access to endpoints due to failed pipeline
> Enable endpoints V2

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
Update the API for the new endpoint
> [PIL-1467-API] Fix API

- resources/public/api/conf/common/overview.md
> PIL-1463 - API Reference Guide

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
We need to declare explicit security for every endpoint in order to deploy our api
> Add explicit security for uktr put endpoint

- it/test/uk/gov/hmrc/pillar2submissionapi/BTNSubmissionISpec.scala
- it/test/uk/gov/hmrc/pillar2submissionapi/UKTaxReturnISpec.scala
- it/test/uk/gov/hmrc/pillar2submissionapi/base/IntegrationSpecBase.scala
This change was to add integration tests as part of [PIL-1373](https://jira.tools.tax.service.gov.uk/browse/PIL-1373) ensuring that agent's could make requests from any of the 3 endpoints of the api
* Added happy path scenario for submitBTN as agent
* Added happy path scenario for submit/amendUKTR as agent
> PIL-1373 - Added integration tests for agents auth

- resources/public/api/conf/common/overview.md
remove link to service guide because it isn't quite ready
> [PIL-1581-link] Remove link to service guide

- resources/public/api/conf/common/errors.md
- resources/public/api/conf/common/testing.md
Remove links to development and qa
> [PIL-1615-service-guide-link] Remove links to lower environments

- app/uk/gov/hmrc/pillar2submissionapi/models/belowthresholdnotification/SubmitBTNSuccessResponse.scala
- it/test/uk/gov/hmrc/pillar2submissionapi/BTNSubmissionISpec.scala
- test/uk/gov/hmrc/pillar2submissionapi/controllers/BTNSubmissionControllerSpec.scala
- test/uk/gov/hmrc/pillar2submissionapi/services/SubmitBTNServiceSpec.scala
> [PIL-1348] Fix response schema for BTN

- conf/submission.routes
- resources/public/api/conf/1.0/application.yaml
> [PIL-1580-headers] Add X-Pillar2-Id header to openAPI docs

- conf/submission.routes
- resources/public/api/conf/1.0/application.yaml
Solid error responses are added to submit UKTR, amend UKTR and submit BTN in open api.
> PIL : 1600 - Provide solid error response examples in our openAPI spec

- app/uk/gov/hmrc/pillar2submissionapi/controllers/actions/AuthenticatedIdentifierAction.scala
- app/uk/gov/hmrc/pillar2submissionapi/services/SubmitBTNService.scala
- app/uk/gov/hmrc/pillar2submissionapi/services/UKTaxReturnService.scala
Remove payload logging because we don't know what will be in the payloads
> [PIL-1709-logging] Remove payloads from logging statements

- app/uk/gov/hmrc/pillar2submissionapi/connectors/TestOrganisationConnector.scala
- conf/setup.routes
- test/uk/gov/hmrc/pillar2submissionapi/connectors/TestOrganisationConnectorSpec.scala
Include _submission data_ in the summary and error responses
> PIL-1644: Update testOrg DELETE endpoint documentation

- README.md
This is to maintain consistency and resemblance to downstream
> PIL-1806: Align service paths with EPIDs

- app/uk/gov/hmrc/pillar2submissionapi/config/AppConfig.scala
- app/uk/gov/hmrc/pillar2submissionapi/controllers/platform/DocumentationController.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/PublishTestOnlyOas.scala
- project/plugins.sbt
- resources/public/api/conf/1.0/testOnly/application.yaml
- resources/public/api/conf/testOnly/application.yaml
This allows for environment-dependent versioning of the OpenAPI Specification. Sbt command `publishTestOnlyOas`  to create and publish the specification has also been added.
> PIL-1643: Enable testOnly OpenAPI Specification

- it/test/uk/gov/hmrc/pillar2submissionapi/controllers/platform/DocumentationControllerISpec.scala
Adds a unit test for https://github.com/hmrc/pillar2-submission-api/pull/91
> PIL-1643: OAS Versioning - unit test

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
> [PIL-1912-fix-server-urls] Fix server urls in openAPI doc

- project/JsonToYaml.scala
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Deploy Obligations and Submissions endpoint to ET
> [PIL-1912-deploy-oas-endpoint] Deploy obligations and submissions to ET

- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Update API docs to show mandatory header
> [PIL-1912-update-mandatory-header] Update mandatory header info

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
- resources/public/api/conf/common/overview.md
- resources/public/api/conf/common/testing.md
Updates to error messages for PIL-1819, PIL1820, PIL-1826 and PIL-1862
Updates to overview.md and testing.md to reflect restructured service guide
> Pil 1876 update error messages

- app/uk/gov/hmrc/pillar2submissionapi/controllers/Pillar2ErrorHandler.scala
- test/uk/gov/hmrc/pillar2submissionapi/controllers/Pillar2ErrorHandlerSpec.scala
- Added specific error code handling for common HTTP client errors (400, 408, 413, 415)
- Implemented descriptive error codes (e.g., "BAD_REQUEST" for 400) instead of numeric codes
- Added comprehensive test coverage for all handled client error cases
- To provide more meaningful error responses to API clients
- To maintain consistency with standard HTTP error code conventions
> PIL-1864 - Add client error handling

- API Testing/pillar2/03-orn/Retrieve ORN.bru
Bruno script added for Retrieve ORN backend
> PIL - 1633 : Retrieve ORN backend

- API Testing/pillar2-external-test-stub/99-qa/btn/unauthorized.bru
- API Testing/pillar2-external-test-stub/99-qa/oas/Unauthorized.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/Delete Organisation.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/Duplicate Submission.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/No Submission Found.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/Unauthorized.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/Valid Amendment.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/Valid Retrieval.bru
- API Testing/pillar2-external-test-stub/99-qa/orn/filedDateGIR in future (Amend).bru
- API Testing/pillar2-external-test-stub/99-qa/orn/filedDateGIR in future.bru
Adds tests for the introduced check and fixes failing tests.
> PIL-1942: filedDateGIR validation

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Adds the error in https://github.com/hmrc/pillar2-submission-api/pull/131 to OAS.
> PIL-1968: Add INCORRECT_HEADER_VALUE error to OAS

- conf/swagger.yml
Update advice for error 003 for SubmitUKTR to include checks on amendment window.
> Update for PIL-1997

- conf/swagger.yml
Update 422 errors to ensure a consistent format.
> PIL 2080   422 errors

- conf/swagger.yml
Update 003 error for Submit Overseas Return Notification and Amend Overseas Return Notification
> PIL-2020 Update 422 error message

- API Testing/environments/qa.bru
Removes an extra forward slash
> NOJIRA - Fix URL in QA Auth

- conf/swagger.yml
Slight text and formatting changes to make sure the error references match the errors as represented on the OAS page and follow the same structure.
> PIL-2021 - Standardise error content

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
We have agreed these APIs can be deployed to externaltest
> [PIL-2133-orn] Add ORN endpoints to externaltest

- conf/swagger.yml
- project/AppDependencies.scala
- project/plugins.sbt
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Spotted by @kjawltd, this payload would fail business validation
> NOJIRA - Update UKTR Liability request body in docs

- conf/swagger.yml
Updates to clarify UK only submissions and accounting period.
> Update UKTR 093 error

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
> Pil 2084 amendment window updates

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Adds a BTN validation rule for when an accounting period is under enquiry.
> PIL-2052: BTN - underEnquiry validation

- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
OAS changes following https://github.com/hmrc/pillar2-submission-api/pull/163
> PIL-2367: Generate OAS for doc changes

- conf/swagger.yml
- resources/public/api/conf/1.0/application.yaml
- resources/public/api/conf/1.0/testOnly/application.yaml
Fixes a lurking documentation error that violates the new field validation (length >= 1 && length <= 4)
> PIL-2415: Fix doc error
